language: cpp
compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cmake --version
  - gcc -v
  - sudo apt-get install -y libboost-dev

script:
  - mkdir build && cd build && cmake .. && make

notifications:
  email:
    - guweigang@bullsoft.org
    - shangyuanchun@bullsoft.org
